### ISSUE TITLE
Reorganize model directories

### ISSUE THREAD

**Issue by damonbayer** [CDCgov/pyrenew-hew#101]
This issue refers to the location-level directories. These currently contain a flat list of poorly named files. This is already difficult to navigate and will be increasingly so as we add more fable models and pyrenew models.
I propose having a common `data` and `figures` directory and a separate directory for each model's specific output.

- `data`
- `pyrenew-e`
- `pyrenew-ew`
- `fable`
- `figures`

**Comment by SamuelBrand1** [comment]
For clarification... this is a reorganistion _within_ each of the model definition folders?

**Comment by SamuelBrand1** [comment]
Assuming the above is true, I think the simplest sequence is to do #119 (or some other PR that closes #57) then reorg the internal structure of each location-reportdate directory.

**Comment by damonbayer** [comment]
Started working on this, (see edited original post) but got a bit lost. I think it would be helpful to first develop a data dictionary-like resource about what these files are and what they contain.

**Comment by damonbayer** [comment]
I'm wondering if we should actually put everything here in a `pyrenew-e` directory.

**Comment by damonbayer** [comment]
Updated the initial post with my current thinking.
