### ISSUE TITLE
Move reused / reusable R functions from `nssp_demo` into the `hewr` package

### ISSUE THREAD

**Issue by dylanhmorris** [CDCgov/pyrenew-hew#103]

**Comment by dylanhmorris** [comment]
> Would be good to have a function for this, like I have [here](https://github.com/CDCgov/pyrenew-hew/pull/89/files#diff-bbd92d76bb54e9be317cc2b02ce6366371e5920f7d71675d4905cbb0d34e20a3R28)

_Originally posted by @damonbayer in https://github.com/CDCgov/pyrenew-hew/pull/102#discussion_r1828229649_

**Comment by damonbayer** [comment]
I think we are in a good spot with this after https://github.com/CDCgov/pyrenew-hew/pull/154
