### ISSUE TITLE
Create demo data and forecasts

### ISSUE THREAD

**Issue by damonbayer** [CDCgov/pyrenew-hew#105]
This will allow us to develop on local machines and share demo figures on github or a package website

## Steps

- [ ] #116
- [ ] #128

**Comment by SamuelBrand1** [comment]
I think this is actually a good thing to add; then we:

- [ ] Add unit tests #75 
- [ ] Add new features eg #110

**Comment by damonbayer** [comment]
@SamuelBrand1 testing is a great use case!

**Comment by SamuelBrand1** [comment]
At a glance, the `.json` datafile for the vignette example should work as a test example.

**Comment by SamuelBrand1** [comment]
Actually `inf_to_hosp_pmf` field is missing from the `stan_data.json`... @damonbayer could you pass a suitable `.json` datafile for test usage?

**Comment by SamuelBrand1** [comment]
Update: it wasn't very hard to create a suitable test `.json` file.
