### ISSUE TITLE
Investigate NA forecasts

### ISSUE THREAD

**Issue by damonbayer** [CDCgov/pyrenew-hew#127]
`pyrenew-test-output/influenza_r_2024-11-12_f_2024-08-29_t_2024-11-11/AK/baseline_ts_count_ed_visits_forecast.parquet`

forecast column appears to be entirely NA

**Comment by SamuelBrand1** [comment]
> It does not support missing values. You can complete missing values in the data with imputed values (e.g. with [tidyr::fill()](https://tidyr.tidyverse.org/reference/fill.html), or by fitting a different model type and then calling [fabletools::interpolate()](https://fabletools.tidyverts.org/reference/reexports.html)) before fitting the model.

https://fable.tidyverts.org/reference/ETS.html

This is probably the issue here

**Comment by damonbayer** [comment]
@SamuelBrand1 The problem is logging the forecast targets. Sometimes counts are 0, and the forecast functions do not like `log(0) = -Inf` values

https://github.com/CDCgov/pyrenew-hew/blob/dbcfb6b862530feb454613934e359c1915678a8a/pipelines/timeseries_forecasts.R#L80-L81

**Comment by damonbayer** [comment]
@SamuelBrand1 Can you implement a fix?

**Comment by SamuelBrand1** [comment]
> @SamuelBrand1 The problem is logging the forecast targets. Sometimes counts are 0, and the forecast functions do not like `log(0) = -Inf` values
> 
> https://github.com/CDCgov/pyrenew-hew/blob/dbcfb6b862530feb454613934e359c1915678a8a/pipelines/timeseries_forecasts.R#L80-L81

Nice spot. We have an offset for the scoring, so I think it is most consistent to use that here.
