### ISSUE TITLE
Automatically delete container when Pull Requests are merged

### ISSUE THREAD

**Issue by damonbayer** [CDCgov/pyrenew-hew#132]
The container registry is filling up with tags from merged PR's. Is it possible to automatically delete these when the PR is merged?

![CleanShot 2024-11-18 at 09 39 29@2x](https://github.com/user-attachments/assets/ab296b06-60b4-4efa-a416-c33bf90d7e1c)

**Comment by gvegayon** [comment]
After doing some research, it seems that there's no registry-agnostic way of deleting images. So my initial plan of doing this in the new action that builds the container in two steps ([link](https://github.com/CDCgov/cfa-actions/pull/5)) won't be supporting that for the moment. The proposed solution: Add another workflow that triggers the merge event of a PR ([ref](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#running-your-pull_request_target-workflow-when-a-pull-request-merges)). I'll start working on that ASAP.
