### ISSUE TITLE
Test for expected files created from a full inference->scoring run

### ISSUE THREAD

**Issue by SamuelBrand1** [CDCgov/pyrenew-hew#139]
> @SamuelBrand1 #135 was supposed to help with that. It's not written as a formal test, but that is the plan in #126. Surprisingly, for this PR, it runs without throwing an error, even though the baseline forecasts aren't being fit.

That suggests that we want something to return this failure in part of the run?

_Originally posted by @SamuelBrand1 in https://github.com/CDCgov/pyrenew-hew/issues/136#issuecomment-2485782984_
            
This issue suggests that we want a test to check if the expected files have been generated where expected at the end of a full run.

Obviously, this doesn't eliminate needing correctness tests on each of the components of the run.

**Comment by damonbayer** [comment]
Closing in favor of https://github.com/CDCgov/pyrenew-hew/issues/216
