### ISSUE TITLE
Generate test data programmatically

### ISSUE THREAD

**Issue by damonbayer** [CDCgov/pyrenew-hew#149]
> > Rather than commit test data in `.csv` and `.tsv` format, it might be cleaner to generate these programatically. The test data was created by assuming 14 day doubling time growth in the eval data with Poisson link, and other ED visit causes to be daily Poisson(100) iid distributed.
> 
> I think I am in favor of this, but it may complicate multi-lingual testing.

Maybe make it an issue and move forwards?

_Originally posted by @SamuelBrand1 in https://github.com/CDCgov/pyrenew-hew/issues/148#issuecomment-2488972717_

**Comment by SamuelBrand1** [comment]
This is linked to #182 as well, i.e. should everything be programmatically generated?

**Comment by damonbayer** [comment]
Closing in favor of https://github.com/CDCgov/pyrenew-hew/issues/216

**Comment by SamuelBrand1** [comment]
This is a sub-task of #216

**Comment by SamuelBrand1** [comment]
This requires a form of parameter estimate parquet.
