### ISSUE TITLE
CI for model test run

### ISSUE THREAD

**Issue by SamuelBrand1** [CDCgov/pyrenew-hew#155]
Yes, let's try to get this running in CI before tackling https://github.com/CDCgov/pyrenew-hew/issues/101

_Originally posted by @damonbayer in https://github.com/CDCgov/pyrenew-hew/pull/148#discussion_r1850969993_
            
As discussed above, having a CI test for the local test run (with increasingly stringent tests is/as we discover bugs) would be good.

_Also_, having the light run prod as CI to check for bugs in the "raw" data ingestion as planned #126 should cover the prod process.

**Comment by damonbayer** [comment]
Closing in favor of https://github.com/CDCgov/pyrenew-hew/issues/216
