### ISSUE TITLE
Clarify repository scope and rename accordingly

### ISSUE THREAD

**Issue by damonbayer** [CDCgov/pyrenew-hew#18]
This repository will host a single model class (name is to be determined, I will use `model_class` in this writeup). `model_class` is a model which can optionally account for observations of:

1. NHSN Hospital Admissions
2. NSSP Emergency Department Admissions
3. Pathogen concentrations in wastewater

The data and priors used with `model_class` define a particular `model_instance`.
At a minimum, we will use two different `model_instance`s: one each for COVID and Flu models.
Depending on data availability, data quality, and model performance, we will need to use different `model_instance`s at different times.
We will likely run multiple `model_instance`s at the same time for the same pathogen so that we can compare results and use simpler models as a fallback for more complex models which may be more difficult to fit at various times.

Because all `model_instance`s rely on the same `model_class`, it will be efficient for each `model_instance` to rely on shared infrastructure for running models and processing their outputs. Some of this infrastructure will live in this repository, while more generic infrastructure may live in other repositories (https://github.com/CDCgov/forecasttools-py).

Given the above,  `pyrenew-covid-wastewater` seems like an inappropriate repository name.

I am requesting feedback on the above description and suggestions for a new repo name 
EDIT: and model class name

@dylanhmorris @AFg6K7h4fhy2 @kaitejohnson @sbidari

**Comment by kaitejohnson** [comment]
Well-scoped -- I think my understanding is that this is the repo where the specification of the `model_class` and the pre and post-processing of the input data and outputs occurs. 

In that case, I would call this `pyrenew-forecasts` or something of the sort, which indicates that the tool being used to create the `model_class` is pyrenew and the output being generated are forecasts, and the `model_instance`s (defined by priors, data, pathogen, etc.) all share the class and output type.

**Comment by damonbayer** [comment]
I think `pyrenew-forecasts` is too generic because I believe other PyRenew forecast models such as https://github.com/CDCgov/pyrenew-flu-light will exist and require different infrastructure.

My latest idea is `pyrenew-hew` (pronounced pie-renew-hue) for **H**ospital admissions, Emergency department admissions, and **W**astewater. This could be the name of both the model class and the repository.

**Comment by kaitejohnson** [comment]
I'm a fan! Forgot the other `model_classes` that are being developed!

**Comment by damonbayer** [comment]
Seems like we have agreed on pyrenew-hue based on face-to-face conversations.

**Comment by seabbs** [comment]
Can you sync the why here for tracking? I struggle to see the reason for hue but also that is dyslexia for you.

**Comment by damonbayer** [comment]
@seabbs I meant to write "hew" and have edited my previous comment.
