### ISSUE TITLE
Make idata text file a `.tsv` rather than a `.csv` for consistency.

### ISSUE THREAD

**Issue by dylanhmorris** [CDCgov/pyrenew-hew#194]
https://github.com/CDCgov/pyrenew-hew/blob/10c8776aefd1663bf39020586d1269519228b40f/pipelines/generate_predictive.py#L40-L43

**Comment by damonbayer** [comment]
I'm planning to skip this step entirely once we have the desired functionality in forecasttools https://github.com/CDCgov/forecasttools-py/issues/18
