### ISSUE TITLE
Run `forecast_state` end-to-end test on a GitHub-hosted runner in CI

### ISSUE THREAD

**Issue by damonbayer** [CDCgov/pyrenew-hew#216]
We should run `main` from [forecast_state.py](https://github.com/CDCgov/pyrenew-hew/blob/main/pipelines/forecast_state.py) on a GitHub-hosted runner in CI.

It would be great if the files created from this workflow were easily downloadable (especially the resulting dashboard page).

This function expects to be passed `facility_level_nssp_data_dir` and `state_level_nssp_data_dir` and then generates data to be used for model fitting.

The existing test data in https://github.com/CDCgov/pyrenew-hew/tree/main/pipelines/tests/covid-19_r_2024-01-29_f_2023-11-01_t_2024-01-29/model_runs/TD/data is one step too "processed." This level of data should be generated during the test.

I think this may need to be broken up into smaller issues and PR's to keep things manageable for reviewers.

**Comment by SamuelBrand1** [comment]
Is the data schema recorded anywhere?

**Comment by SamuelBrand1** [comment]
I think this is really only a two step process:

- [ ] Create a function to resolve #149 
- [ ] Write a gh action to do the function above and then run `forecast_state`

**Comment by SamuelBrand1** [comment]
> It would be great if the files created from this workflow were easily downloadable (especially the resulting dashboard page).

I think you can do this from the command line if you want:

```bash
gh run download <run-id>
```
using the `run-id`.

**Comment by damonbayer** [comment]
@SamuelBrand1 I was thinking using the [`post-artifact` action](https://github.com/CDCgov/cfa-actions/tree/main/post-artifact) from cfa-actions

**Comment by gvegayon** [comment]
> @SamuelBrand1 I was thinking of using the [`post-artifact` action](https://github.com/CDCgov/cfa-actions/tree/main/post-artifact) from cfa-actions

We could spin that action to directly post the artifact on an issue instead of a PR (if there's none). From the programmatic point of view, PRs are, in fact, issues, so I don't think it should be too complicated it to make it more general :).
