### ISSUE TITLE
Create structure to support fitting flu models with existing non-ww model

### ISSUE THREAD

**Issue by damonbayer** [CDCgov/pyrenew-hew#22]

**Comment by seabbs** [comment]
maybe make this a subissue of #23

**Comment by seabbs** [comment]
though perhaps it isn't if there needs to be choices about Flu first

**Comment by damonbayer** [comment]
Will rephrase the issue title. This is more about "creating another instance of the existing model that fits NSSP flu data". It is the same as the existing model, but with different priors.

https://github.com/CDCgov/pyrenew-covid-wastewater/issues/23 is an actual change to the model structure. There could be two instances of that model: one for Flu and one for COVID.
