### ISSUE TITLE
Codecov project status not available

### ISSUE THREAD

**Issue by damonbayer** [CDCgov/pyrenew-hew#244]
Not sure why project status is not available for pyrenew-hew:
[![codecov](https://codecov.io/gh/CDCgov/pyrenew-hew/graph/badge.svg?token=TJM5F3SF4K)](https://codecov.io/gh/CDCgov/pyrenew-hew)

but is available for pyrenew:
[![codecov](https://codecov.io/gh/CDCgov/pyrenew/graph/badge.svg?token=7Z06HOMYR1)](https://codecov.io/gh/CDCgov/pyrenew)

@sbidari can you investigate if we need to set up something else with codecov?

**Comment by sbidari** [comment]
I think codecov bot comment on PRs opened after #233 was merged includes both project and diff coverage. Not sure why the status badge is not updated but will revisit this later.

**Comment by damonbayer** [comment]
Supposedly you can also get per-flag badges, but those also don't work for us:

[![codecov](https://codecov.io/gh/CDCgov/pyrenew-hew/graph/badge.svg?token=TJM5F3SF4K?flag=hewr)](https://codecov.io/gh/CDCgov/pyrenew-hew)

[![codecov](https://codecov.io/gh/CDCgov/pyrenew-hew/graph/badge.svg?token=TJM5F3SF4K?flag=pyrenew_hew)](https://codecov.io/gh/CDCgov/pyrenew-hew)

[![codecov](https://codecov.io/gh/CDCgov/pyrenew-hew/graph/badge.svg?token=TJM5F3SF4K?flag=pipelines)](https://codecov.io/gh/CDCgov/pyrenew-hew)

**Comment by sbidari** [comment]
The coverage status badge is displaying coverage now. Coverage badge for flag-specific coverage:

hewr: [![hewr](https://codecov.io/gh/CDCgov/pyrenew-hew/branch/main/graph/badge.svg?flag=hewr)](https://codecov.io/gh/CDCgov/pyrenew-hew)

pyrenew_hew: [![pyrenew_hew](https://codecov.io/gh/CDCgov/pyrenew-hew/graph/badge.svg?flag=pyrenew_hew)](https://codecov.io/gh/CDCgov/pyrenew-hew)

pipelines: [![pipelines](https://codecov.io/gh/CDCgov/pyrenew-hew/graph/badge.svg?flag=pipelines)](https://codecov.io/gh/CDCgov/pyrenew-hew)

**Comment by sbidari** [comment]
Closing as completed

**Comment by damonbayer** [comment]
@sbidari can we add these badges to the repo readme?
