### ISSUE TITLE
Containerize pyrenew-hew

### ISSUE THREAD

**Issue by damonbayer** [CDCgov/pyrenew-hew#44]
We should do this automatically on pushes to main using a self-hosted runner, as in cfa-epinow2-pipeline https://github.com/CDCgov/cfa-epinow2-pipeline/blob/main/.github/workflows/containers-and-az-pool.yaml

**Comment by damonbayer** [comment]
@gvegayon would you be interested in helping with this?

**Comment by gvegayon** [comment]
We need @jkislin to help us get the secrets and necessary stuff for connecting to Azure services

**Comment by damonbayer** [comment]
Container is implemented in https://github.com/CDCgov/pyrenew-hew/pull/78

**Comment by gvegayon** [comment]
@dylanhmorris may have access to the Azure credentials. I have, but I don't have access to the secrets of this repo.

**Comment by damonbayer** [comment]
Resolved this with @gvegayon over Teams.
