### ISSUE TITLE
Run a model in CI

### ISSUE THREAD

**Issue by damonbayer** [CDCgov/pyrenew-hew#52]
This will help us catch any incompatibilities with PyRenew updates (e.g., https://github.com/CDCgov/pyrenew-hew/issues/50)

**Comment by seabbs** [comment]
you should also be able to trigger this CI from pyrenew as a reverse dependency check

**Comment by SamuelBrand1** [comment]
Does #247 close this?

**Comment by damonbayer** [comment]
@SamuelBrand1 Yes, but I am interested in the reverse-dependency check that @seabbs mentioned.
