### ISSUE TITLE
A model to generate $N(t)$.

### ISSUE THREAD

**Issue by SamuelBrand1** [CDCgov/pyrenew-hew#53]
This issue is aimed at selecting a method for forecasting the _independent_ part of the denominator of the fraction:

```math
P(t) = {X(t) \over X(t) + N(t)}.
```

Where $X(t)$ is a target pathogen which is modelled using a sophisticated method e.g. `pyrenew-hew`, and $N(t)$ are the remainder of the numerator.

This approach assumes that independence of $X(t)$ is $N(t)$ is reasonable; for example when $N(t)$ is a mix of some other respiratory virus incidence but pre-dominantly non-infectious disease causes.

**Comment by seabbs** [comment]
It would be interesting to use this approach as the baseline for the main target as well.

**Comment by SamuelBrand1** [comment]
Agreed, I think the specific choice of an equi-weighted ETS + SARIMA with auto structure selection is likely to be robust baseline choice for short term forecasts

**Comment by SamuelBrand1** [comment]
Closed by #102
