### ISSUE TITLE
Reorganize repository based on current plans

### ISSUE THREAD

**Issue by damonbayer** [CDCgov/pyrenew-hew#57]
There are a few issues with the current repo structure:

1. Our NSSP model started as a "demo," hence the `nssp_demo` folder, but it is now the main offering of the repo.
2. We are collecting a variety of other "demo" scripts, currently stored in the `notebooks` folder.

I would like to reorganize the repo to make things a bit more clear. I think I will have a better idea of how to do that once we have run things in azure.

**Comment by SamuelBrand1** [comment]
My 2p worth, and this might be better implemented over more than one repo:

Have a structure of:

- `tools`: thats `pyrenew-hew` etc which do the analysis. This should be callable from projects in this repo.
- `projects`: thats discrete projects we want to work on in the open e.g. `nssp`.
- `demos` -> `docs` as vignettes.

**Comment by damonbayer** [comment]
Current thinking:

- `pyrenew-hew`: setup as a python library that has the PyRenew model(s)
- `utils_R`: R utility scripts that can be `source`d or could be set up as an R package
- `utils_py`:
- `pipeline`: scripts related to running the pipeline
  - could be further separated into different `pipeline` folders if we have different pipelines
- `demos`: vignettes / docs

**Comment by dylanhmorris** [comment]
Largely agree, but I think we can and should avoid `import`-able/`source`-able middle ground between pipeline scripts and packaged code. So I'd suggest the above except:

- Bundle anything reused enough to be a `utils-py` into `pyrenew-hew.utils`
- Any `utils_R` that don't belong in `pipeline` could be a micro-package called `hewR` or something

**Comment by SamuelBrand1** [comment]
- [ ] `pyrenew-hew`: setup as a python library that has the PyRenew model(s)
- [ ] `utils_R`: R utility scripts that can be `source`d or could be set up as an R package
- [ ] `utils_py`: Python utility scripts that can be `import`ed.
- [ ] `pipeline`: scripts related to running the pipeline
  - could be further separated into different `pipeline` folders if we have different pipelines
- [ ] `demos`: vignettes / docs
