### ISSUE TITLE
unit testing for `nssp_demo`

### ISSUE THREAD

**Issue by SamuelBrand1** [CDCgov/pyrenew-hew#75]
In #68 we reverted away the unit tests for the denominator forecast functions without replacement, and I've noted that I don't think we have unit tests for any of the functions in `nssp_demo`.

I think we should increase our coverage here to catch small issues before we test in an end-to-end/CD manner as well.

**Comment by damonbayer** [comment]
Closing. We still need testing, but `nssp_demo` no longer exists.
