### ISSUE TITLE
Produce baseline forecasts of the numerator

### ISSUE THREAD

**Issue by dylanhmorris** [CDCgov/pyrenew-hew#80]
Agreed, I think the specific choice of an equi-weighted ETS + SARIMA with auto structure selection is likely to be robust baseline choice for short term forecasts

_Originally posted by @SamuelBrand1 in https://github.com/CDCgov/pyrenew-hew/issues/53#issuecomment-2413222050_
            

- [x] #92
- [x] #94

**Comment by damonbayer** [comment]
When doing this, we should unify the numerator and denominator models, as suggested in https://github.com/CDCgov/pyrenew-hew/pull/54#issuecomment-2442672649.

**Comment by dylanhmorris** [comment]
While doing this, @SamuelBrand1 also plans to add computation of the FluSight/COVIDHub baseline model, leveraging functionality in [`epipredict`](https://github.com/cmu-delphi/epipredict)

**Comment by SamuelBrand1** [comment]
Closed as completed subtasks.
