### ISSUE TITLE
Checkpointing for single location workflow

### ISSUE THREAD

**Issue by dylanhmorris** [CDCgov/pyrenew-hew#81]
> It would be nice to be able to skip steps (or start at a certain step) based on some command line arg. Then, for example, you could trivially rerun the post-processing without refitting the model.

_Originally posted by @damonbayer in https://github.com/CDCgov/pyrenew-hew/pull/78#discussion_r1819642037_

**Comment by damonbayer** [comment]
Closing in favor of #48
