### ISSUE TITLE
Consider directory structure for individual model runs

### ISSUE THREAD

**Issue by dylanhmorris** [CDCgov/pyrenew-hew#84]
> Should we have a more descriptive directory name to indicate something about when the model was run or what version of the code was used? or just a unique identifier?

_Originally posted by @damonbayer in https://github.com/CDCgov/pyrenew-hew/pull/78#discussion_r1819644610_

**Comment by damonbayer** [comment]
related: https://github.com/CDCgov/pyrenew-hew/issues/62

**Comment by dylanhmorris** [comment]
Also related #136

**Comment by damonbayer** [comment]
Closing in favor of https://github.com/CDCgov/pyrenew-hew/issues/156
