### ISSUE TITLE
Fit to national timeseries

### ISSUE THREAD

**Issue by dylanhmorris** [CDCgov/pyrenew-hew#90]
We will also want to consider bottom-up aggregation of state forecasts, but even if/when we find and approach we like, it will be useful to have a national fit as a comparison and/or fallback.

**Comment by dylanhmorris** [comment]
A basic national timeseries fit is implemented in #102

**Comment by SamuelBrand1** [comment]
> A basic national timeseries fit is implemented in #102

Might be worth doing this for each CDC region as well.
