### ISSUE TITLE
CDC flat baseline

### ISSUE THREAD

**Issue by SamuelBrand1** [CDCgov/pyrenew-hew#94]
This is a task of #80 .

The goal of this task is to use the baseline forecaster https://cmu-delphi.github.io/epipredict/reference/cdc_baseline_forecaster.html to produce a useful comparison baseline of the _proportion_ of a target pathogen.

Because this is a simple flatline, my view is that this is easiest achieved with a logit-transform on the proportion data, forecasting that and then gathering the prediction quantiles.

## Alternative
We can follow the same pattern as the main forecasting approach: that is forecasting the numerator and using an existing denominator forecast to construct proportions.

**Comment by dylanhmorris** [comment]
This will be closed by #102
